import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import employeesJson from '../libs/employeesData';
import { useRouter } from 'next/router';
import Link from 'next/link';

import Navbar from '../components/nav/Navbar';

export default function Home() {
	const router = useRouter();

	const handleOnClick = (guid) => {
		router.push(`/detail/${guid}`);
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>305 Medical Center Employees</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Navbar />

			<main className={styles.main}>
				<h1 className={styles.title}>305 Medical Center Employees</h1>

				<div className={styles.employeesContainer}>
					{employeesJson.map((employee) => {
						return (
							<p
								className={styles.employeesCards}
								key={employee.guid}
								onClick={() => handleOnClick(employee.guid)}>
								{employee.name}, {employee.occupation}
							</p>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}>
				<p>FEU2 class course assignment by Jessica Warr - </p>
				<p>Built in Next.Js with hard coded JSON, Formik & NextAuth</p>
			</footer>
		</div>
	);
}
