const employeesJson = [
	{
		pid: '1',
		guid: '001',
		name: 'Monica Sanchez',
		age: 35,
		gender: 'Female',
		occupation: 'Family Physician',
		phone: '305-964-2120',
		isActive: true,
	},
	{
		pid: '2',
		guid: '002',
		name: 'Michael Warren',
		age: 42,
		gender: 'Male',
		occupation: 'Family Physician',
		phone: '305-964-2121',
		isActive: true,
	},
	{
		pid: '3',
		guid: '003',
		name: 'Sofia Loren',
		age: 32,
		gender: 'Female',
		occupation: 'Medical Secretary',
		phone: '305-714-3130',
		isActive: true,
	},
	{
		pid: '4',
		guid: '004',
		name: 'Penelope Cruz',
		age: '29',
		gender: 'Female',
		occupation: 'Nurse',
		phone: '305-808-4140',
		isActive: true,
	},
	{
		pid: '5',
		guid: '005',
		name: 'Benjamin Michel',
		age: '39',
		gender: 'Male',
		occupation: 'Nurse',
		phone: '305-705-5150',
		isActive: false,
	},
	{
		pid: '6',
		guid: '006',
		name: 'Drake Graham',
		age: '35',
		gender: 'Male',
		occupation: 'Chiropractor',
		phone: '305-912-6160',
		isActive: true,
	},
	{
		pid: '7',
		guid: '007',
		name: 'Nicki Onika',
		age: '40',
		gender: 'Female',
		occupation: 'Gyncologist',
		phone: '305-701-7170',
		isActive: true,
	},
	{
		pid: '8',
		guid: '008',
		name: 'Daniel Washington',
		age: '41',
		gender: 'Male',
		occupation: 'Radiologist',
		phone: '305-889-8180',
		isActive: true,
	},
	{
		pid: '9',
		guid: '009',
		name: 'Ashleigh Judd',
		age: '43',
		gender: 'Female',
		occupation: 'Anesthesiologist',
		phone: '305-999-9190',
		isActive: true,
	},
];

export default employeesJson;
